version: '3'

services:
  server:
    build: ./
    expose:
     - ${API_PORT}
    environment:
      API_HOST: ${API_HOST}
      API_PORT: ${API_PORT}
    ports:
      - ${API_PORT}:${API_PORT}
    volumes:
      - ./src:/srv/app/real-time-analytics